{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.10.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.10.0.jar",
          "size": 51304,
          "sha512": "57119d650d9a0b5474a0f87e3dff007ba4a396980f50fc9b440e39f5f34dade5736fff7554cc163d681efd3df2a73bde016794a9f5f3d233d27f7331a7d7f82c",
          "sha256": "4ffdf6a8dcee48589c041ff2b6c920636cf319b1ab9624148005d39e5b2a6164",
          "sha1": "aea557d6e59237ff6562a855c2f3ef5c0d840fad",
          "md5": "726f9e49667836a6b9271435b59355f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.10.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.10.0.jar",
          "size": 51304,
          "sha512": "57119d650d9a0b5474a0f87e3dff007ba4a396980f50fc9b440e39f5f34dade5736fff7554cc163d681efd3df2a73bde016794a9f5f3d233d27f7331a7d7f82c",
          "sha256": "4ffdf6a8dcee48589c041ff2b6c920636cf319b1ab9624148005d39e5b2a6164",
          "sha1": "aea557d6e59237ff6562a855c2f3ef5c0d840fad",
          "md5": "726f9e49667836a6b9271435b59355f5"
        }
      ]
    }
  ]
}
