{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "2.37.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-2.37.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-2.37.1.jar",
          "size": 8853,
          "sha512": "308ebe5c82b754bae28014d3818b7ab1154fef4eb0d38d2ccb77dcd4cc71636e6c4b4e8197238920e7b20e7468b26c7b58b71855f67ff5f853418ed25a067a39",
          "sha256": "1d48dc7317eb35ef5c9a6fe45bdaff7e035651a3260505958ec350d69a411e12",
          "sha1": "7e0155630c1fd68f9a0ff5d83aa7896e7f04cfb2",
          "md5": "9b6a70a0d2ee8b043c3b8cab043f6aa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-2.37.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-2.37.1.jar",
          "size": 8853,
          "sha512": "308ebe5c82b754bae28014d3818b7ab1154fef4eb0d38d2ccb77dcd4cc71636e6c4b4e8197238920e7b20e7468b26c7b58b71855f67ff5f853418ed25a067a39",
          "sha256": "1d48dc7317eb35ef5c9a6fe45bdaff7e035651a3260505958ec350d69a411e12",
          "sha1": "7e0155630c1fd68f9a0ff5d83aa7896e7f04cfb2",
          "md5": "9b6a70a0d2ee8b043c3b8cab043f6aa5"
        }
      ]
    }
  ]
}
