{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.12.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.12.4.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.12.4.jar",
          "size": 51304,
          "sha512": "2e5072545ac1ff07c0c4a1d4c89e4a77fb73bd52cdbd6c3e3a0d552948b43052f19d547c101a11a6664f21c73e3986c3246f4f14150fea7a62220cc5daa6fa74",
          "sha256": "585ca5af3e8647de1ecf91c218a36cabbe69e90b1b256d2eadeb9905d118f4d1",
          "sha1": "7bdcea19b4fc51d70f248d97db58f404613a432d",
          "md5": "4ff19e49d03a410348bc059c0305a024"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.12.4.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.12.4.jar",
          "size": 51304,
          "sha512": "2e5072545ac1ff07c0c4a1d4c89e4a77fb73bd52cdbd6c3e3a0d552948b43052f19d547c101a11a6664f21c73e3986c3246f4f14150fea7a62220cc5daa6fa74",
          "sha256": "585ca5af3e8647de1ecf91c218a36cabbe69e90b1b256d2eadeb9905d118f4d1",
          "sha1": "7bdcea19b4fc51d70f248d97db58f404613a432d",
          "md5": "4ff19e49d03a410348bc059c0305a024"
        }
      ]
    }
  ]
}
