{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.4.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.4.0.jar",
          "size": 37639,
          "sha512": "05438b25561ce157aae12522d695251ed8f109d190ad998bd88ecc367405d112c879d2165db214ccbb2c9c4b5c0d5d771672cd97e14bade9512ef4bdddf3814c",
          "sha256": "0d874098b61294dc92cbc284eeb0e0d3eb8b6f705f42e513f460d23f84b86399",
          "sha1": "1bb9f0d9ca28238bc4a5cdba22c0660d92a60842",
          "md5": "24baa3c17ea18dda34f746ced99ed458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.4.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.4.0.jar",
          "size": 37639,
          "sha512": "05438b25561ce157aae12522d695251ed8f109d190ad998bd88ecc367405d112c879d2165db214ccbb2c9c4b5c0d5d771672cd97e14bade9512ef4bdddf3814c",
          "sha256": "0d874098b61294dc92cbc284eeb0e0d3eb8b6f705f42e513f460d23f84b86399",
          "sha1": "1bb9f0d9ca28238bc4a5cdba22c0660d92a60842",
          "md5": "24baa3c17ea18dda34f746ced99ed458"
        }
      ]
    }
  ]
}
