{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.3.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.3.jar",
          "size": 17661,
          "sha512": "061b62514d70aa8a3dd5678356c37dc934543d31ce5116ae13e652f43580d6fc0eb214e943f67ecccf3daa6c8fdab41626bc843b8fd0472e02619d6ab91c0cc5",
          "sha256": "a684e73306759ef0b80c4cf4e12ba52676541e0b39e242098cd1e99e726a8158",
          "sha1": "bb4e7a6c7f1518805d74b95ca4286221c3d03cec",
          "md5": "547cc18315d75d1bc53ac6562f626586"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.3.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.3.jar",
          "size": 17661,
          "sha512": "061b62514d70aa8a3dd5678356c37dc934543d31ce5116ae13e652f43580d6fc0eb214e943f67ecccf3daa6c8fdab41626bc843b8fd0472e02619d6ab91c0cc5",
          "sha256": "a684e73306759ef0b80c4cf4e12ba52676541e0b39e242098cd1e99e726a8158",
          "sha1": "bb4e7a6c7f1518805d74b95ca4286221c3d03cec",
          "md5": "547cc18315d75d1bc53ac6562f626586"
        }
      ]
    }
  ]
}
