{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.1.jar",
          "size": 17661,
          "sha512": "8c90f0d372d83de5dc6d613190ae3c5d203f97f16cd6a8030b79ed1d93ab4e9be9570441f15e41cf4c9bba96684ac22c6f441b2e0a123e1d8beb0dbb83e4b1b7",
          "sha256": "c2dedf46a36289df5460cdf6e5091d3f5192bdb9cbf2504e8a96cf557249367e",
          "sha1": "a9c6d4345d80c06f5d8d90c9346542c7a88ba856",
          "md5": "90e860b1a4cbedf61a985c687b73e83d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.1.jar",
          "size": 17661,
          "sha512": "8c90f0d372d83de5dc6d613190ae3c5d203f97f16cd6a8030b79ed1d93ab4e9be9570441f15e41cf4c9bba96684ac22c6f441b2e0a123e1d8beb0dbb83e4b1b7",
          "sha256": "c2dedf46a36289df5460cdf6e5091d3f5192bdb9cbf2504e8a96cf557249367e",
          "sha1": "a9c6d4345d80c06f5d8d90c9346542c7a88ba856",
          "md5": "90e860b1a4cbedf61a985c687b73e83d"
        }
      ]
    }
  ]
}
