{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.13.3.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.13.3.jar",
          "size": 17661,
          "sha512": "4e2aa83dbbf408a181aaf4d743d94f5b733147b4c08213da0c27a27225d9abe1f5d534c72e0e4fc03af0e7d359ba8b0f098c613be41f9137e7555be4bdce604a",
          "sha256": "b282d8ba0766af5bbc3ac2d31863a5f5b7e7a1f25c78bb1b5aaaa46e2ed4eff1",
          "sha1": "2ebec059ea53551cabd8438e3331409ea2b051f5",
          "md5": "200198510cefb07ecfedd504b6d1af78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.13.3.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.13.3.jar",
          "size": 17661,
          "sha512": "4e2aa83dbbf408a181aaf4d743d94f5b733147b4c08213da0c27a27225d9abe1f5d534c72e0e4fc03af0e7d359ba8b0f098c613be41f9137e7555be4bdce604a",
          "sha256": "b282d8ba0766af5bbc3ac2d31863a5f5b7e7a1f25c78bb1b5aaaa46e2ed4eff1",
          "sha1": "2ebec059ea53551cabd8438e3331409ea2b051f5",
          "md5": "200198510cefb07ecfedd504b6d1af78"
        }
      ]
    }
  ]
}
