{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.16.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.16.0.jar",
          "size": 18307,
          "sha512": "0acc6c16e05f332395b557427b94a09fd2eef8dbca5a83a645bce6b3afd20d84fcba0cca62667b601b971bf46eeda058b3f7f0e2da49e2c9da6bd28c6785985c",
          "sha256": "39b1f812602faa9e69483bd71a9a86540fc87b7ef36c4c98a8b72bfdfe4f3a02",
          "sha1": "8fac7fa6ca6b1f37ed13d2ad60eccfd57585462e",
          "md5": "4cdacf4d20bab7eee57c47644dd00431"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.16.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.16.0.jar",
          "size": 18307,
          "sha512": "0acc6c16e05f332395b557427b94a09fd2eef8dbca5a83a645bce6b3afd20d84fcba0cca62667b601b971bf46eeda058b3f7f0e2da49e2c9da6bd28c6785985c",
          "sha256": "39b1f812602faa9e69483bd71a9a86540fc87b7ef36c4c98a8b72bfdfe4f3a02",
          "sha1": "8fac7fa6ca6b1f37ed13d2ad60eccfd57585462e",
          "md5": "4cdacf4d20bab7eee57c47644dd00431"
        }
      ]
    }
  ]
}
