{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.13.4.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.13.4.jar",
          "size": 51304,
          "sha512": "93d27df1cde879b7ce38cd8247e2b734945dc8d06012f83a9a2746f1d1bc8a6ccf506b3ade64fdc87d779351d63cf913d724431e91914b94a0d906d2e09fdd88",
          "sha256": "5b27bd88e6eb6fe5fbb79eb3e9a7bddae2128de9bda8abc40edcfb042715e83c",
          "sha1": "7a40027e353c95bd607d8989f97acc29f8988fe6",
          "md5": "0683eb534e988af39aa86b441a4c0588"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.13.4.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.13.4.jar",
          "size": 51304,
          "sha512": "93d27df1cde879b7ce38cd8247e2b734945dc8d06012f83a9a2746f1d1bc8a6ccf506b3ade64fdc87d779351d63cf913d724431e91914b94a0d906d2e09fdd88",
          "sha256": "5b27bd88e6eb6fe5fbb79eb3e9a7bddae2128de9bda8abc40edcfb042715e83c",
          "sha1": "7a40027e353c95bd607d8989f97acc29f8988fe6",
          "md5": "0683eb534e988af39aa86b441a4c0588"
        }
      ]
    }
  ]
}
