{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.14.1.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.14.1.jar",
          "size": 51304,
          "sha512": "87fa4f6111940f66418b7c881b38379f0105c392b276670f917522cda21c45bc2f6f9dcc99346dcb717f676fc3ecbb604fc38e72607ed470fc6a83ace60ebd09",
          "sha256": "824112bb49ca4fd98875831e4835cd9b468c148d40958f9008eaacc20b0c27cc",
          "sha1": "700a7a2e6b1493126c04d96625f37b722554d014",
          "md5": "e642d96ee4c0eda0e93a73d78d3c123b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.14.1.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.14.1.jar",
          "size": 51304,
          "sha512": "87fa4f6111940f66418b7c881b38379f0105c392b276670f917522cda21c45bc2f6f9dcc99346dcb717f676fc3ecbb604fc38e72607ed470fc6a83ace60ebd09",
          "sha256": "824112bb49ca4fd98875831e4835cd9b468c148d40958f9008eaacc20b0c27cc",
          "sha1": "700a7a2e6b1493126c04d96625f37b722554d014",
          "md5": "e642d96ee4c0eda0e93a73d78d3c123b"
        }
      ]
    }
  ]
}
