{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.5.1.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.5.1.jar",
          "size": 38448,
          "sha512": "b07f8014b9ca5ec2ab297206b5e7cf628a17a2e798915b085ad2857100d3a7aba9a06a4c9f133f28bf7e23d846b369f253d295e72fb153bacf76745462d534c9",
          "sha256": "5f7eae96bc1cae769a94a429e4ff43ba39c36e9e3363a562436c62c323547da4",
          "sha1": "471f0539c49c8991b22991380a55395a1f885ff7",
          "md5": "100a53e9a5613e481bd7bf17c9ede6a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.5.1.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.5.1.jar",
          "size": 38448,
          "sha512": "b07f8014b9ca5ec2ab297206b5e7cf628a17a2e798915b085ad2857100d3a7aba9a06a4c9f133f28bf7e23d846b369f253d295e72fb153bacf76745462d534c9",
          "sha256": "5f7eae96bc1cae769a94a429e4ff43ba39c36e9e3363a562436c62c323547da4",
          "sha1": "471f0539c49c8991b22991380a55395a1f885ff7",
          "md5": "100a53e9a5613e481bd7bf17c9ede6a0"
        }
      ]
    }
  ]
}
