{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.3.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.3.0.jar",
          "size": 8253,
          "sha512": "61e6c7759979dbc53a6cd7eac0335bd1c207bd5ad6821fcc47c7a9f93300346203a3d690b421705c43af47478510fd93a9b920b81e1a2f49b47f97faf3f12898",
          "sha256": "d5d55ee6de7d515da8ee3bd83d50699f1ebcb15e67209465700528d59ac50670",
          "sha1": "1dd022db967cceb4aa6d716b74e66be59501f488",
          "md5": "52442a56c5ac0254a606c2d4893d14f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.3.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.3.0.jar",
          "size": 8253,
          "sha512": "61e6c7759979dbc53a6cd7eac0335bd1c207bd5ad6821fcc47c7a9f93300346203a3d690b421705c43af47478510fd93a9b920b81e1a2f49b47f97faf3f12898",
          "sha256": "d5d55ee6de7d515da8ee3bd83d50699f1ebcb15e67209465700528d59ac50670",
          "sha1": "1dd022db967cceb4aa6d716b74e66be59501f488",
          "md5": "52442a56c5ac0254a606c2d4893d14f2"
        }
      ]
    }
  ]
}
