{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.11.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.11.0.jar",
          "size": 17660,
          "sha512": "15f21862b0cc6b8712bc12040563b04e335f3699674c7eaa146c5c92867de1d0d19b6ff7f6c836a48963bf5ebe46f34af16fc15b3ae4d6adcfc08fb2c0883c4e",
          "sha256": "121d4434efe79877d2b96e59563f16335b1d50bec44fd0b64b328ea074d65ac7",
          "sha1": "779a6ef4edcfaa02bff7218469c41027cd5bd712",
          "md5": "f6b1e4a279aefe28b5979e4db1d6f26a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.11.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.11.0.jar",
          "size": 17660,
          "sha512": "15f21862b0cc6b8712bc12040563b04e335f3699674c7eaa146c5c92867de1d0d19b6ff7f6c836a48963bf5ebe46f34af16fc15b3ae4d6adcfc08fb2c0883c4e",
          "sha256": "121d4434efe79877d2b96e59563f16335b1d50bec44fd0b64b328ea074d65ac7",
          "sha1": "779a6ef4edcfaa02bff7218469c41027cd5bd712",
          "md5": "f6b1e4a279aefe28b5979e4db1d6f26a"
        }
      ]
    }
  ]
}
