{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "2.38.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-2.38.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-2.38.0.jar",
          "size": 8853,
          "sha512": "5a006745e7924098c6bd9b0365b0bf6ab28601a779ed34981e632887699513802692ae7fa0c0391adc156aa2ef8925a8c1e86203c1b4f092bc86b8ed5f9463a0",
          "sha256": "9da5f75f5ef2d4151a0884343a2eab8ed9a7de76c60a4175f8fb58d57a56b070",
          "sha1": "3159dbfa42f4b47a3879401b2d3093cb59c7930e",
          "md5": "73ac67e2a27207d6f375ec89cbb4ab69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-2.38.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-2.38.0.jar",
          "size": 8853,
          "sha512": "5a006745e7924098c6bd9b0365b0bf6ab28601a779ed34981e632887699513802692ae7fa0c0391adc156aa2ef8925a8c1e86203c1b4f092bc86b8ed5f9463a0",
          "sha256": "9da5f75f5ef2d4151a0884343a2eab8ed9a7de76c60a4175f8fb58d57a56b070",
          "sha1": "3159dbfa42f4b47a3879401b2d3093cb59c7930e",
          "md5": "73ac67e2a27207d6f375ec89cbb4ab69"
        }
      ]
    }
  ]
}
