{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.12.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.12.3.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.12.3.jar",
          "size": 17661,
          "sha512": "eea47c9bea4770865bc35b8474efca8eeb237385822788523a95f79f0ce2f70b6807017358febf1155608c16336d59475e7b04ba8bf7ee3cc1d2566c682862b2",
          "sha256": "f007441f4413225f4870dce447246a0154bc0636fda98d489c192724eccb1df6",
          "sha1": "25c03d792e3b5bcbafaae194b2b9e6635283b674",
          "md5": "c16f066dd523f244f651deed62f6429c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.12.3.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.12.3.jar",
          "size": 17661,
          "sha512": "eea47c9bea4770865bc35b8474efca8eeb237385822788523a95f79f0ce2f70b6807017358febf1155608c16336d59475e7b04ba8bf7ee3cc1d2566c682862b2",
          "sha256": "f007441f4413225f4870dce447246a0154bc0636fda98d489c192724eccb1df6",
          "sha1": "25c03d792e3b5bcbafaae194b2b9e6635283b674",
          "md5": "c16f066dd523f244f651deed62f6429c"
        }
      ]
    }
  ]
}
