{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.17.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.17.1.jar",
          "size": 18307,
          "sha512": "857a3d0390a15c4c2a6a568a516ca96d1b301bc6c1852c46fe61c6c7c371172a7b50c6c5d09b8be34cc01f5e164068748630b656f88f7153584725ef6bf0f695",
          "sha256": "1eea0a581567f5fe8251825db6ddcf079ff0268f7f7ba04b57fec5759bf24867",
          "sha1": "f2bda04e687922a36b79d9cb988e275b2fdc6033",
          "md5": "596fe4f0ba1a5b08628802bf1d9c8ad7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.17.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.17.1.jar",
          "size": 18307,
          "sha512": "857a3d0390a15c4c2a6a568a516ca96d1b301bc6c1852c46fe61c6c7c371172a7b50c6c5d09b8be34cc01f5e164068748630b656f88f7153584725ef6bf0f695",
          "sha256": "1eea0a581567f5fe8251825db6ddcf079ff0268f7f7ba04b57fec5759bf24867",
          "sha1": "f2bda04e687922a36b79d9cb988e275b2fdc6033",
          "md5": "596fe4f0ba1a5b08628802bf1d9c8ad7"
        }
      ]
    }
  ]
}
