{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.12.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.12.0.jar",
          "size": 17660,
          "sha512": "3d7d3658ae3ef5cba009723702893e93853aa952a924d05c66a073b5936725bde903ffe5b484510f81ae8af2abd3afd20dca348003537a2f565c73c4d22605b1",
          "sha256": "56520a95ed631beb3d8be260288ed950000e303fb412a7a93ed35c673ce0c7c3",
          "sha1": "75de33a47f779011810f444901f13263017383c8",
          "md5": "16718d36c7e5f23fd4d85108649f9875"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.12.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.12.0.jar",
          "size": 17660,
          "sha512": "3d7d3658ae3ef5cba009723702893e93853aa952a924d05c66a073b5936725bde903ffe5b484510f81ae8af2abd3afd20dca348003537a2f565c73c4d22605b1",
          "sha256": "56520a95ed631beb3d8be260288ed950000e303fb412a7a93ed35c673ce0c7c3",
          "sha1": "75de33a47f779011810f444901f13263017383c8",
          "md5": "16718d36c7e5f23fd4d85108649f9875"
        }
      ]
    }
  ]
}
