{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.8.2.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.8.2.jar",
          "size": 17661,
          "sha512": "0b09f27a721bb3a871d9cae6a66a8d48868a323d24aaf659fef77f0306569970cd1f0cd9c86e9538268126e0e87b1c0c6247789d62cecef7c6958271f41547a3",
          "sha256": "35cd56636df3917c3b7816cc9c6af4abea3d75e03c99502d4e773671e214616d",
          "sha1": "a842c2953593b327ab76d5d1f925b2b6d5d1926e",
          "md5": "9fb5add48ec468264f02f09e14517341"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.8.2.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.8.2.jar",
          "size": 17661,
          "sha512": "0b09f27a721bb3a871d9cae6a66a8d48868a323d24aaf659fef77f0306569970cd1f0cd9c86e9538268126e0e87b1c0c6247789d62cecef7c6958271f41547a3",
          "sha256": "35cd56636df3917c3b7816cc9c6af4abea3d75e03c99502d4e773671e214616d",
          "sha1": "a842c2953593b327ab76d5d1f925b2b6d5d1926e",
          "md5": "9fb5add48ec468264f02f09e14517341"
        }
      ]
    }
  ]
}
