{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.5.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.5.1.jar",
          "size": 12302,
          "sha512": "4ff3c76a5f38507fe26ee5c86c66fc64266b85621319896c4e0900b494e00f137980a44a4614b7f37d8a5e78bcf880c8ce6e61da155ec53ab586e2feca259583",
          "sha256": "d838c48a5115368b00f6788d4e9873290a30c74d0e657c5dd75873ff29e2c8bf",
          "sha1": "a8621cc348967d641c99793ac496c9bf39269296",
          "md5": "ec5d1b04494839959e0bb4a6aa9f8377"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.5.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.5.1.jar",
          "size": 12302,
          "sha512": "4ff3c76a5f38507fe26ee5c86c66fc64266b85621319896c4e0900b494e00f137980a44a4614b7f37d8a5e78bcf880c8ce6e61da155ec53ab586e2feca259583",
          "sha256": "d838c48a5115368b00f6788d4e9873290a30c74d0e657c5dd75873ff29e2c8bf",
          "sha1": "a8621cc348967d641c99793ac496c9bf39269296",
          "md5": "ec5d1b04494839959e0bb4a6aa9f8377"
        }
      ]
    }
  ]
}
