{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.14.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.2.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.2.jar",
          "size": 17661,
          "sha512": "bd7539cda2e4eae4c4b0548024bbd5346adeb322c215b90fc58cf17e76595424c65248993344df91fc09ed67462c2475533cab1c10d0701959c5335c8dafe59e",
          "sha256": "8e83cc0cceb59546b0cf073df94995e80e9dc76933c7fc5940dbef0eec7dda0b",
          "sha1": "93968c39ed252378e79d3d4c349b54008968bc4d",
          "md5": "8a597b3b4e1123561b4d6b328897e597"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.2.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.2.jar",
          "size": 17661,
          "sha512": "bd7539cda2e4eae4c4b0548024bbd5346adeb322c215b90fc58cf17e76595424c65248993344df91fc09ed67462c2475533cab1c10d0701959c5335c8dafe59e",
          "sha256": "8e83cc0cceb59546b0cf073df94995e80e9dc76933c7fc5940dbef0eec7dda0b",
          "sha1": "93968c39ed252378e79d3d4c349b54008968bc4d",
          "md5": "8a597b3b4e1123561b4d6b328897e597"
        }
      ]
    }
  ]
}
