{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.18.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.18.0.jar",
          "size": 18391,
          "sha512": "9436cac83f988983a62a74c74f55fe4d5c6390e1859ddbac60637be4a31c62bbe28349d8682d3588e672e906824a148e7a883a0ed10cdb39d1c15598fbbc4f26",
          "sha256": "f33dfeef6515386a94dfad89ea737c56520e2f5d40d2727a6ceff9681358ef96",
          "sha1": "49f633fc38620c5bf8372f48b6ae64ecda54f942",
          "md5": "70cd7b8284e4ae6ab0af34234a27e0a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.18.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.18.0.jar",
          "size": 18391,
          "sha512": "9436cac83f988983a62a74c74f55fe4d5c6390e1859ddbac60637be4a31c62bbe28349d8682d3588e672e906824a148e7a883a0ed10cdb39d1c15598fbbc4f26",
          "sha256": "f33dfeef6515386a94dfad89ea737c56520e2f5d40d2727a6ceff9681358ef96",
          "sha1": "49f633fc38620c5bf8372f48b6ae64ecda54f942",
          "md5": "70cd7b8284e4ae6ab0af34234a27e0a0"
        }
      ]
    }
  ]
}
