{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.11.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.11.0.jar",
          "size": 51304,
          "sha512": "3d5f54719c462bcade63c803dca33bf59014b103315ae03965bde644ebcb210549e6e81d9e68f6d7d13e17231669536aee2b9d6ec8952fcd18da89a897383793",
          "sha256": "711aa40978f9a5e321f8ea971aed9dcb03fd4c77c2253ab1de6751057a035a50",
          "sha1": "ae2359093d1ac8cec89cf903b256def5af4e170f",
          "md5": "85c2eb3fd216e2d9ab0737671a9bfe3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.11.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.11.0.jar",
          "size": 51304,
          "sha512": "3d5f54719c462bcade63c803dca33bf59014b103315ae03965bde644ebcb210549e6e81d9e68f6d7d13e17231669536aee2b9d6ec8952fcd18da89a897383793",
          "sha256": "711aa40978f9a5e321f8ea971aed9dcb03fd4c77c2253ab1de6751057a035a50",
          "sha1": "ae2359093d1ac8cec89cf903b256def5af4e170f",
          "md5": "85c2eb3fd216e2d9ab0737671a9bfe3a"
        }
      ]
    }
  ]
}
