{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.8.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.8.0.jar",
          "size": 45714,
          "sha512": "36e557736759d120f631b3f8b9d8f6c733feb018b221bbbc85b38686dda215cf2e79524194ad031e6494a7acb8e13d83480b017406ea6ee5e8630c35e2320dca",
          "sha256": "1dca81a35d09363369bc7dc058a32437cf06a1152129e19bc43fd048a7e85b9d",
          "sha1": "79af8662ed75c2d9a758b0e9e9e5d9f6de9b8683",
          "md5": "3f3d1e1a6540ed054f9388f3a418f3a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.8.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.8.0.jar",
          "size": 45714,
          "sha512": "36e557736759d120f631b3f8b9d8f6c733feb018b221bbbc85b38686dda215cf2e79524194ad031e6494a7acb8e13d83480b017406ea6ee5e8630c35e2320dca",
          "sha256": "1dca81a35d09363369bc7dc058a32437cf06a1152129e19bc43fd048a7e85b9d",
          "sha1": "79af8662ed75c2d9a758b0e9e9e5d9f6de9b8683",
          "md5": "3f3d1e1a6540ed054f9388f3a418f3a0"
        }
      ]
    }
  ]
}
