{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.8.1.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.8.1.jar",
          "size": 52463,
          "sha512": "9e096399b5d78d3750a883b9d7b1b82f2d38e0dc66e8426ba1a24344850e0861242e61c33e8398f8af93f0f88933ca9e77cdd89988a75e0b2d3a8fcc49961927",
          "sha256": "df0ab5c74df4e851a8cb0ce6ad94ef71bb52c4a7adc5c752f79267ddb14bcde1",
          "sha1": "7ae62650d6e008a73f8342fb33e8da8d8d2b3171",
          "md5": "6beec048661dc554c30ec376d21038ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.8.1.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.8.1.jar",
          "size": 52463,
          "sha512": "9e096399b5d78d3750a883b9d7b1b82f2d38e0dc66e8426ba1a24344850e0861242e61c33e8398f8af93f0f88933ca9e77cdd89988a75e0b2d3a8fcc49961927",
          "sha256": "df0ab5c74df4e851a8cb0ce6ad94ef71bb52c4a7adc5c752f79267ddb14bcde1",
          "sha1": "7ae62650d6e008a73f8342fb33e8da8d8d2b3171",
          "md5": "6beec048661dc554c30ec376d21038ae"
        }
      ]
    }
  ]
}
