{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.4.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.4.1.jar",
          "size": 12321,
          "sha512": "9752e6d68ea4c2063c1f91c33c8fc73783019445c326834ab743744e8de5a05f5ed2667b881fd9db4ef3c881a14b3e83e2862c0b2a15ae83ced9886f63abb927",
          "sha256": "ba500b297b070849dfc5c9e682e7b0c928278993c6dc7efa7da09e44c21d20a6",
          "sha1": "4e9867c50a8bb1adf5b90ac810db9b8f4c3b91ab",
          "md5": "65121aa7d382ae5b343c49bea576e95e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.4.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.4.1.jar",
          "size": 12321,
          "sha512": "9752e6d68ea4c2063c1f91c33c8fc73783019445c326834ab743744e8de5a05f5ed2667b881fd9db4ef3c881a14b3e83e2862c0b2a15ae83ced9886f63abb927",
          "sha256": "ba500b297b070849dfc5c9e682e7b0c928278993c6dc7efa7da09e44c21d20a6",
          "sha1": "4e9867c50a8bb1adf5b90ac810db9b8f4c3b91ab",
          "md5": "65121aa7d382ae5b343c49bea576e95e"
        }
      ]
    }
  ]
}
