{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.14.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.14.0.jar",
          "size": 51304,
          "sha512": "356741851492aca191de2328db0490edf0a49efdb7ab46fc78738f3e41d086ec843b437928a53048df60dce29fc31c8fca041b0e795f4e51b91c8bdc22c394f8",
          "sha256": "88728013fff050880a001a6881781ca53ec00ccc492d2618de450cb204e525b4",
          "sha1": "c33f5a5061ffa2f38e4c73c3e7329ec339938c23",
          "md5": "519c1b81a1a6650758d2324bbf436262"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.14.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.14.0.jar",
          "size": 51304,
          "sha512": "356741851492aca191de2328db0490edf0a49efdb7ab46fc78738f3e41d086ec843b437928a53048df60dce29fc31c8fca041b0e795f4e51b91c8bdc22c394f8",
          "sha256": "88728013fff050880a001a6881781ca53ec00ccc492d2618de450cb204e525b4",
          "sha1": "c33f5a5061ffa2f38e4c73c3e7329ec339938c23",
          "md5": "519c1b81a1a6650758d2324bbf436262"
        }
      ]
    }
  ]
}
