{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.12.2.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.12.2.jar",
          "size": 17660,
          "sha512": "af272b286363b07193df56933d79053de900bf8a08a90ce0d57972d447a40878395ac9faa49229f661e4e6e1e61d8e96f8a984dbf996ba0290c2f7efacc211bc",
          "sha256": "3f1668ec298c7a4cec6ea78ee91be84369f1d6890dff51b25765c0c5c6a55a9d",
          "sha1": "09e9449870fb88beb0ead2b693a25b6d11460784",
          "md5": "e40e6b1015eef94f655fceb90d4503fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.12.2.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.12.2.jar",
          "size": 17660,
          "sha512": "af272b286363b07193df56933d79053de900bf8a08a90ce0d57972d447a40878395ac9faa49229f661e4e6e1e61d8e96f8a984dbf996ba0290c2f7efacc211bc",
          "sha256": "3f1668ec298c7a4cec6ea78ee91be84369f1d6890dff51b25765c0c5c6a55a9d",
          "sha1": "09e9449870fb88beb0ead2b693a25b6d11460784",
          "md5": "e40e6b1015eef94f655fceb90d4503fb"
        }
      ]
    }
  ]
}
