{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.2.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.2.0.jar",
          "size": 31867,
          "sha512": "1d911b00611113e821b39a28695290b85f282af4902b0a8f541f0d81cb831c87c6d990d5cd9732d229dbec7a59fd36af9cfbd0569fc4aec28f0cefd51acc8404",
          "sha256": "204db34c6ef55abf60a8f0e06bed14f02a6a3127d4fe92b2462a0da4890273ab",
          "sha1": "540c2e2d17cc1a63b151bc1dbdf02f1b2de47adc",
          "md5": "7168bcd86f21ca06a6961f734787b323"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.2.0.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.2.0.jar",
          "size": 31867,
          "sha512": "1d911b00611113e821b39a28695290b85f282af4902b0a8f541f0d81cb831c87c6d990d5cd9732d229dbec7a59fd36af9cfbd0569fc4aec28f0cefd51acc8404",
          "sha256": "204db34c6ef55abf60a8f0e06bed14f02a6a3127d4fe92b2462a0da4890273ab",
          "sha1": "540c2e2d17cc1a63b151bc1dbdf02f1b2de47adc",
          "md5": "7168bcd86f21ca06a6961f734787b323"
        }
      ]
    }
  ]
}
