{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.4.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.4.0.jar",
          "size": 12321,
          "sha512": "30c7c4114e9c9d4f9e69a753c5c4e77cb06111b64737a51dad20a0cad5334b6ab5ae13f499a41684c990044fe9300e09bf9f14460332b79cdb52bd4eac00a3e8",
          "sha256": "dca165a95f8fb3d5e93da6aec3f7fa29035ea0e0163b436cbeebd93e202116f9",
          "sha1": "5d699a15966db2802716d8f7ec3c178e03044d77",
          "md5": "e11cf79e218aa9791631b4f447536e13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.4.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.4.0.jar",
          "size": 12321,
          "sha512": "30c7c4114e9c9d4f9e69a753c5c4e77cb06111b64737a51dad20a0cad5334b6ab5ae13f499a41684c990044fe9300e09bf9f14460332b79cdb52bd4eac00a3e8",
          "sha256": "dca165a95f8fb3d5e93da6aec3f7fa29035ea0e0163b436cbeebd93e202116f9",
          "sha1": "5d699a15966db2802716d8f7ec3c178e03044d77",
          "md5": "e11cf79e218aa9791631b4f447536e13"
        }
      ]
    }
  ]
}
