{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.8.2.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.8.2.jar",
          "size": 51304,
          "sha512": "3bebbf95c2c514c1ebabc4f7529868cd0731fe0375327fa35ee25d83f727c049e391e3cfe433f5dd129fb555c3cbfbfa75b1c70c835c18050dba31d9d7b0a842",
          "sha256": "fa2f0f818d01b4eae663f7ca5da691d749f8fe394f118a9d93eb91022b73a7a8",
          "sha1": "70fcdce328665317bc0e0257a77a14132e85d028",
          "md5": "271f2ba0e9df7fdb6d8f0dcf2544e2be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.8.2.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.8.2.jar",
          "size": 51304,
          "sha512": "3bebbf95c2c514c1ebabc4f7529868cd0731fe0375327fa35ee25d83f727c049e391e3cfe433f5dd129fb555c3cbfbfa75b1c70c835c18050dba31d9d7b0a842",
          "sha256": "fa2f0f818d01b4eae663f7ca5da691d749f8fe394f118a9d93eb91022b73a7a8",
          "sha1": "70fcdce328665317bc0e0257a77a14132e85d028",
          "md5": "271f2ba0e9df7fdb6d8f0dcf2544e2be"
        }
      ]
    }
  ]
}
