{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.15.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.15.0.jar",
          "size": 17662,
          "sha512": "3ce0076ff059207379812681346e63190f3de4044de5f5263c29b70288e2ff0e905cde78a433afb2015ac7349362706911b6c10a02b87cbaf45cd6396800cedd",
          "sha256": "08f9fbe315fa94475dc40c589ad859e40f1cb3b3b5b08bfe6bff9cc57f414db2",
          "sha1": "38e0a1ddfcd93bc469be37a2aa60ded66aaf847e",
          "md5": "0c2f009ac65bbd173c3c0ee4a8881b8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.15.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.15.0.jar",
          "size": 17662,
          "sha512": "3ce0076ff059207379812681346e63190f3de4044de5f5263c29b70288e2ff0e905cde78a433afb2015ac7349362706911b6c10a02b87cbaf45cd6396800cedd",
          "sha256": "08f9fbe315fa94475dc40c589ad859e40f1cb3b3b5b08bfe6bff9cc57f414db2",
          "sha1": "38e0a1ddfcd93bc469be37a2aa60ded66aaf847e",
          "md5": "0c2f009ac65bbd173c3c0ee4a8881b8e"
        }
      ]
    }
  ]
}
