{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.0.jar",
          "size": 17661,
          "sha512": "72e4a686f2c272b72400b23429557e5dd1435b9d75a072aced0b4b44573137b51983cbce89d2a318223061dbb00902848c481e9c18ab86a09970a4490107a586",
          "sha256": "28271817b7b3875b52e9e0cf4c4d9140da7e2a77560ed7943242256fc798d5db",
          "sha1": "8c21267f8a145e9e362c5d9c4d2eb34f16c8c870",
          "md5": "58b12ab207a0cbeb3727182895cfe7db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.14.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.14.0.jar",
          "size": 17661,
          "sha512": "72e4a686f2c272b72400b23429557e5dd1435b9d75a072aced0b4b44573137b51983cbce89d2a318223061dbb00902848c481e9c18ab86a09970a4490107a586",
          "sha256": "28271817b7b3875b52e9e0cf4c4d9140da7e2a77560ed7943242256fc798d5db",
          "sha1": "8c21267f8a145e9e362c5d9c4d2eb34f16c8c870",
          "md5": "58b12ab207a0cbeb3727182895cfe7db"
        }
      ]
    }
  ]
}
