{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.18.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.18.1.jar",
          "size": 18391,
          "sha512": "8e07789cd2ea6fea52da5b2cf521b90e12b15ae6f5a380555ee7c85ba15327d2aff73c876010a2d70ed025af19e83b98079ee8a4cd1452408585627738f2bb76",
          "sha256": "7d786acac449ac90b5526a9c0fb639f5eac681dffb77cd362b1f3621fa69582a",
          "sha1": "920c8a5ef4c8d24a4d05d224fcc55882bf853a43",
          "md5": "eb91baebe1882a00344bfc2ce463df0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.18.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.18.1.jar",
          "size": 18391,
          "sha512": "8e07789cd2ea6fea52da5b2cf521b90e12b15ae6f5a380555ee7c85ba15327d2aff73c876010a2d70ed025af19e83b98079ee8a4cd1452408585627738f2bb76",
          "sha256": "7d786acac449ac90b5526a9c0fb639f5eac681dffb77cd362b1f3621fa69582a",
          "sha1": "920c8a5ef4c8d24a4d05d224fcc55882bf853a43",
          "md5": "eb91baebe1882a00344bfc2ce463df0d"
        }
      ]
    }
  ]
}
