{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.13.4.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.13.4.jar",
          "size": 17661,
          "sha512": "f88523e3583c9f03b2cb64547981704fe561e305a471412d82468af79c715c16564c1a4659a44a1e82971d5a362ad086e65aa8bce47aedb3ef4cf43c9183f038",
          "sha256": "22fe3681153dff9808eb209141efe4e1f00222c55c37578a8d55a75a44246785",
          "sha1": "8964be0f1f0af8a77e41ef71e7e83e010c7b9735",
          "md5": "cd470a945c13eb3d688997017db3355d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.13.4.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.13.4.jar",
          "size": 17661,
          "sha512": "f88523e3583c9f03b2cb64547981704fe561e305a471412d82468af79c715c16564c1a4659a44a1e82971d5a362ad086e65aa8bce47aedb3ef4cf43c9183f038",
          "sha256": "22fe3681153dff9808eb209141efe4e1f00222c55c37578a8d55a75a44246785",
          "sha1": "8964be0f1f0af8a77e41ef71e7e83e010c7b9735",
          "md5": "cd470a945c13eb3d688997017db3355d"
        }
      ]
    }
  ]
}
