{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.8.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.8.1.jar",
          "size": 17661,
          "sha512": "28d8098e72ac43daec85bc4c3f3b6a80f49b925597cccea4b7e51867ef07d45a6ec1fec341bd0b80325f429e2b297cd6d583e36886c6dadb5a79b788b53a5a98",
          "sha256": "c676af6c61e9a5e30afb73c12ad8fd1d50be9cd7bf8773eeb5e6ae870fcbff75",
          "sha1": "7ba376ace26d31517785f9eab479471d18d61f8d",
          "md5": "efe7248606eb750d924c27a4761a7725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.8.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.8.1.jar",
          "size": 17661,
          "sha512": "28d8098e72ac43daec85bc4c3f3b6a80f49b925597cccea4b7e51867ef07d45a6ec1fec341bd0b80325f429e2b297cd6d583e36886c6dadb5a79b788b53a5a98",
          "sha256": "c676af6c61e9a5e30afb73c12ad8fd1d50be9cd7bf8773eeb5e6ae870fcbff75",
          "sha1": "7ba376ace26d31517785f9eab479471d18d61f8d",
          "md5": "efe7248606eb750d924c27a4761a7725"
        }
      ]
    }
  ]
}
