{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-kotlin-plugin",
    "version": "3.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.14.3.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.14.3.jar",
          "size": 51304,
          "sha512": "a1261c723eb16a6492cafa66a2585a1de336b2f88a20d93d4d32fb209f2b311c964e33405f09302083a4e9ad8ea21d883838abbb17d13dc8829ff21d01d63501",
          "sha256": "f19906a4325de2e55d698031336c0045d52c8a2b39bbf09b7d8a798ef34a4f25",
          "sha1": "4249b4aa34e6605943d8c226c5dd1949e6f858e6",
          "md5": "70077e6e005d00defc9775cb2e731879"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-kotlin-plugin-3.14.3.jar",
          "url": "cobrowse-sdk-android-kotlin-plugin-3.14.3.jar",
          "size": 51304,
          "sha512": "a1261c723eb16a6492cafa66a2585a1de336b2f88a20d93d4d32fb209f2b311c964e33405f09302083a4e9ad8ea21d883838abbb17d13dc8829ff21d01d63501",
          "sha256": "f19906a4325de2e55d698031336c0045d52c8a2b39bbf09b7d8a798ef34a4f25",
          "sha1": "4249b4aa34e6605943d8c226c5dd1949e6f858e6",
          "md5": "70077e6e005d00defc9775cb2e731879"
        }
      ]
    }
  ]
}
