{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.8.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.8.0.jar",
          "size": 17661,
          "sha512": "9b0689b23fca810d75c8ee2ce5be07dc04bbe550778faec3fb61daeb81f96ccc9061714a4d7627ba49da49eae4040f08a2365d8caa3de79cdc60b52a11a39a4b",
          "sha256": "4cd8d495503f9ab280c4544b64cf9884d525b128dc302ceb135b356b41a77799",
          "sha1": "b103966bfb1d92ffc9776d1728c6ae12dca36870",
          "md5": "d3598f41e6ffe55bd4a8af034aff226b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.8.0.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.8.0.jar",
          "size": 17661,
          "sha512": "9b0689b23fca810d75c8ee2ce5be07dc04bbe550778faec3fb61daeb81f96ccc9061714a4d7627ba49da49eae4040f08a2365d8caa3de79cdc60b52a11a39a4b",
          "sha256": "4cd8d495503f9ab280c4544b64cf9884d525b128dc302ceb135b356b41a77799",
          "sha1": "b103966bfb1d92ffc9776d1728c6ae12dca36870",
          "md5": "d3598f41e6ffe55bd4a8af034aff226b"
        }
      ]
    }
  ]
}
