{
  "formatVersion": "1.1",
  "component": {
    "group": "io.cobrowse",
    "module": "cobrowse-sdk-android-gradle-plugin",
    "version": "3.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.7.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.7.1.jar",
          "size": 12304,
          "sha512": "ed738df4120941c020188a11fc0666c8cc8c4075ae63d4e9f8e8ae0d2e7cc6e7d672783a2d39ee9968e8a1fb4730b5c182dbbcac07aa1dca2aa9998ded9211af",
          "sha256": "8ebc148f0feabfebb2d406a53d468af13861cb280c5c6f2877fa4d8bace6a1a6",
          "sha1": "61be0941a6639522b8a975a3b11b8df22ca98868",
          "md5": "8ee1b09fa15495aa9989ef10c0a6109d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cobrowse-sdk-android-gradle-plugin-3.7.1.jar",
          "url": "cobrowse-sdk-android-gradle-plugin-3.7.1.jar",
          "size": 12304,
          "sha512": "ed738df4120941c020188a11fc0666c8cc8c4075ae63d4e9f8e8ae0d2e7cc6e7d672783a2d39ee9968e8a1fb4730b5c182dbbcac07aa1dca2aa9998ded9211af",
          "sha256": "8ebc148f0feabfebb2d406a53d468af13861cb280c5c6f2877fa4d8bace6a1a6",
          "sha1": "61be0941a6639522b8a975a3b11b8df22ca98868",
          "md5": "8ee1b09fa15495aa9989ef10c0a6109d"
        }
      ]
    }
  ]
}
